---
# This playbook runs the script to check registry value for allowed null session vulnerability on Windows hosts

- name: AllowedNullSession-check
  hosts: all 
  gather_facts: false
  tasks:
    - name: run powershell script
      script: PSscripts/AllowedNullSession-check.ps1
      
    - name: get content of file
      win_shell: 'c:\temp\AllowedNullSession-check.txt'  
      register: file_content
      
    - name: display content
      debug:
        msg: "{{ file_content.stdout_lines }} "
