---
- name: Obtain information about a registry key property
  hosts: all 
  gather_facts: false
  
  tasks:
    - name: check registry command
      win_reg_stat:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
        name: RestrictAnonymous
      register: RestrictAnonymousValue

    - name: show result
      debug:
        var: RestrictAnonymousValue
